export interface ISCC {
    id_scc: string,
    scc_address?: string | undefined,
    scc_blockchain?: string | undefined,	
    scc_mint_date?: string | undefined,		
    scc_blockchain_status?: string | undefined,		
    scc_retirement_status?: string | undefined,		
    scc_ghg_value?: string | undefined,		
    scc_farmer_fees?: string | undefined,		
    scc_developer_fees?: string | undefined,		
    scc_minter_registry_fees?: string | undefined,	
    scc_registry?: string | undefined,	
    uco_parcel_id?: string | undefined,	
    uco_parcel_area?: string | undefined,	
    uco_parcel_shapefile?: string | undefined,	
    uco_vintage?: string | undefined,	
    uco_country?: string | undefined,	
    uco_project_id?: string | undefined,	
    uco_primary_crop?: string | undefined,	
    uco_project_type?: string | undefined,	
    uco_project_developer?: string | undefined,	
    scc_uco_id: string,	
    uco_wallet_id?: string | undefined,
    onSale?: boolean,
    onChainId: number,
    uploadedBy: string,
}